using System;
using System.Collections.Generic;
using TaskManagerDAL.Models;

namespace TaskManagerDAL.Context
{
    class QuoteInitializer : System.Data.Entity.DropCreateDatabaseIfModelChanges<QuoteContext>
    {
        protected override void Seed(QuoteContext context)
        {
            var quotes = new List<Quote>
            {
                 new Quote{QuoteType="CS-782",Contact="Paul",DueDate=DateTime.Parse("2020-05-16T21:20:58Z"),TaskDescription="Versatile next generation pricing structure",TaskType="flexibility"},
new Quote{QuoteType="PJ-097",Contact="Katharyn",DueDate=DateTime.Parse("2017-05-27T10:54:49Z"),TaskDescription="Universal attitude-oriented process improvement",TaskType="Operative"},
new Quote{QuoteType="CA-771",Contact="Rheba",DueDate=DateTime.Parse("2018-11-06T05:04:31Z"),TaskDescription="Expanded coherent matrices",TaskType="migration"},
new Quote{QuoteType="ST-403",Contact="Irma",DueDate=DateTime.Parse("2018-06-02T05:05:13Z"),TaskDescription="Stand-alone multi-state Graphical User Interface",TaskType="bandwidth-monitored"},
new Quote{QuoteType="LI-756",Contact="Lorilyn",DueDate=DateTime.Parse("2016-10-23T10:37:58Z"),TaskDescription="Reactive next generation secured line",TaskType="Multi-layered"},
new Quote{QuoteType="FH-668",Contact="Tybi",DueDate=DateTime.Parse("2017-09-25T02:12:24Z"),TaskDescription="Synchronised 4th generation process improvement",TaskType="4th generation"},
new Quote{QuoteType="RW-717",Contact="Elly",DueDate=DateTime.Parse("2020-01-28T21:46:28Z"),TaskDescription="Universal 6th generation system engine",TaskType="toolset"},
new Quote{QuoteType="DP-188",Contact="Arne",DueDate=DateTime.Parse("2019-09-19T18:27:32Z"),TaskDescription="Advanced systematic paradigm",TaskType="non-volatile"},
new Quote{QuoteType="NB-543",Contact="Jania",DueDate=DateTime.Parse("2019-11-17T11:19:36Z"),TaskDescription="Vision-oriented bifurcated definition",TaskType="model"},
new Quote{QuoteType="JM-650",Contact="Pansie",DueDate=DateTime.Parse("2016-08-10T05:25:38Z"),TaskDescription="Mandatory responsive projection",TaskType="alliance"},
new Quote{QuoteType="SE-378",Contact="Angelia",DueDate=DateTime.Parse("2018-04-29T08:23:49Z"),TaskDescription="Triple-buffered incremental moratorium",TaskType="intranet"},
new Quote{QuoteType="AM-677",Contact="Kasper",DueDate=DateTime.Parse("2018-11-01T10:03:46Z"),TaskDescription="Cloned motivating orchestration",TaskType="leading edge"},
new Quote{QuoteType="UL-666",Contact="Viki",DueDate=DateTime.Parse("2019-12-24T00:40:23Z"),TaskDescription="Digitized client-server emulation",TaskType="function"},
new Quote{QuoteType="FP-584",Contact="Gizela",DueDate=DateTime.Parse("2016-08-19T01:59:46Z"),TaskDescription="Optional eco-centric array",TaskType="Adaptive"},
new Quote{QuoteType="GE-388",Contact="Nonie",DueDate=DateTime.Parse("2017-02-14T13:31:55Z"),TaskDescription="Function-based motivating initiative",TaskType="bi-directional"},
new Quote{QuoteType="EB-496",Contact="Calv",DueDate=DateTime.Parse("2016-07-07T12:13:39Z"),TaskDescription="Open-architected optimal open system",TaskType="Diverse"},
new Quote{QuoteType="IG-876",Contact="Dawn",DueDate=DateTime.Parse("2019-02-24T07:16:26Z"),TaskDescription="Configurable fresh-thinking service-desk",TaskType="pricing structure"},
new Quote{QuoteType="CX-163",Contact="Sergei",DueDate=DateTime.Parse("2018-11-26T16:21:00Z"),TaskDescription="Devolved mission-critical projection",TaskType="motivating"},
new Quote{QuoteType="NC-522",Contact="Lek",DueDate=DateTime.Parse("2017-04-09T14:25:59Z"),TaskDescription="Enterprise-wide human-resource middleware",TaskType="didactic"},
new Quote{QuoteType="CL-456",Contact="Heywood",DueDate=DateTime.Parse("2018-01-11T23:32:24Z"),TaskDescription="De-engineered local structure",TaskType="modular"},
new Quote{QuoteType="MT-440",Contact="Cymbre",DueDate=DateTime.Parse("2018-09-03T18:31:27Z"),TaskDescription="Adaptive real-time database",TaskType="Intuitive"},
new Quote{QuoteType="KD-021",Contact="Rosina",DueDate=DateTime.Parse("2017-10-07T15:08:10Z"),TaskDescription="Compatible cohesive capability",TaskType="Multi-lateral"},
new Quote{QuoteType="PO-492",Contact="Hall",DueDate=DateTime.Parse("2019-01-18T18:18:07Z"),TaskDescription="Face to face web-enabled instruction set",TaskType="Ameliorated"},
new Quote{QuoteType="LR-683",Contact="Tobie",DueDate=DateTime.Parse("2017-09-16T05:27:49Z"),TaskDescription="Advanced zero defect methodology",TaskType="User-friendly"},
new Quote{QuoteType="EG-376",Contact="Brandy",DueDate=DateTime.Parse("2017-07-03T17:50:00Z"),TaskDescription="Integrated asymmetric focus group",TaskType="initiative"},
new Quote{QuoteType="HI-141",Contact="Nestor",DueDate=DateTime.Parse("2018-12-15T05:27:06Z"),TaskDescription="Profound 6th generation focus group",TaskType="Advanced"},
new Quote{QuoteType="XH-399",Contact="Claretta",DueDate=DateTime.Parse("2019-04-23T23:31:05Z"),TaskDescription="Front-line user-facing orchestration",TaskType="Distributed"},
new Quote{QuoteType="AK-197",Contact="Leone",DueDate=DateTime.Parse("2019-06-20T18:54:28Z"),TaskDescription="Switchable leading edge portal",TaskType="asymmetric"},
new Quote{QuoteType="FZ-084",Contact="Burr",DueDate=DateTime.Parse("2016-07-26T06:16:09Z"),TaskDescription="Centralized dynamic functionalities",TaskType="Graphic Interface"},
new Quote{QuoteType="SK-242",Contact="Amy",DueDate=DateTime.Parse("2018-11-05T16:17:24Z"),TaskDescription="Expanded 6th generation groupware",TaskType="toolset"},
new Quote{QuoteType="OA-682",Contact="Elliot",DueDate=DateTime.Parse("2016-09-08T03:23:53Z"),TaskDescription="Self-enabling solution-oriented policy",TaskType="well-modulated"},
new Quote{QuoteType="IE-480",Contact="Allayne",DueDate=DateTime.Parse("2018-05-06T05:26:16Z"),TaskDescription="Reduced dynamic paradigm",TaskType="instruction set"},
new Quote{QuoteType="TO-452",Contact="Marjory",DueDate=DateTime.Parse("2019-09-19T18:00:29Z"),TaskDescription="Re-engineered zero defect matrices",TaskType="customer loyalty"},
new Quote{QuoteType="SX-246",Contact="Coral",DueDate=DateTime.Parse("2017-01-26T09:07:13Z"),TaskDescription="Networked bifurcated algorithm",TaskType="homogeneous"},
new Quote{QuoteType="SQ-183",Contact="Dominique",DueDate=DateTime.Parse("2018-02-07T06:28:37Z"),TaskDescription="Vision-oriented context-sensitive paradigm",TaskType="systematic"},
new Quote{QuoteType="ZH-875",Contact="Virgil",DueDate=DateTime.Parse("2018-08-30T17:02:29Z"),TaskDescription="Triple-buffered regional service-desk",TaskType="client-server"},
new Quote{QuoteType="TK-145",Contact="Hillery",DueDate=DateTime.Parse("2017-01-11T20:01:03Z"),TaskDescription="User-friendly full-range infrastructure",TaskType="framework"},
new Quote{QuoteType="LF-804",Contact="Cristi",DueDate=DateTime.Parse("2020-07-04T15:20:18Z"),TaskDescription="Front-line tertiary contingency",TaskType="Configurable"},
new Quote{QuoteType="CD-175",Contact="Hildy",DueDate=DateTime.Parse("2018-04-22T21:02:01Z"),TaskDescription="Open-architected client-server functionalities",TaskType="capability"},
new Quote{QuoteType="EN-313",Contact="Skye",DueDate=DateTime.Parse("2018-12-14T21:12:42Z"),TaskDescription="Progressive non-volatile architecture",TaskType="Organized"},
new Quote{QuoteType="EZ-229",Contact="Julieta",DueDate=DateTime.Parse("2017-10-26T16:02:07Z"),TaskDescription="Ergonomic upward-trending orchestration",TaskType="Universal"},
new Quote{QuoteType="YL-816",Contact="Modestia",DueDate=DateTime.Parse("2017-12-05T02:20:42Z"),TaskDescription="Multi-lateral bi-directional task-force",TaskType="Persevering"},
new Quote{QuoteType="FX-414",Contact="Keefer",DueDate=DateTime.Parse("2017-08-13T20:50:05Z"),TaskDescription="Versatile high-level moratorium",TaskType="implementation"},
new Quote{QuoteType="LK-691",Contact="Timoteo",DueDate=DateTime.Parse("2018-11-27T23:58:59Z"),TaskDescription="Vision-oriented fault-tolerant success",TaskType="Re-engineered"},
new Quote{QuoteType="JU-961",Contact="Lin",DueDate=DateTime.Parse("2018-02-24T10:22:08Z"),TaskDescription="Optimized optimizing forecast",TaskType="concept"},
new Quote{QuoteType="JE-981",Contact="Olwen",DueDate=DateTime.Parse("2018-10-18T10:31:53Z"),TaskDescription="Right-sized content-based approach",TaskType="customer loyalty"},
new Quote{QuoteType="UY-844",Contact="Clemmy",DueDate=DateTime.Parse("2016-09-14T23:44:12Z"),TaskDescription="Robust asymmetric matrix",TaskType="Business-focused"},
new Quote{QuoteType="RF-533",Contact="Sisely",DueDate=DateTime.Parse("2018-09-27T15:28:21Z"),TaskDescription="Future-proofed zero administration circuit",TaskType="Devolved"},
new Quote{QuoteType="SG-880",Contact="Benjamin",DueDate=DateTime.Parse("2019-03-23T06:01:45Z"),TaskDescription="Multi-lateral next generation time-frame",TaskType="frame"},
new Quote{QuoteType="MD-071",Contact="Joelie",DueDate=DateTime.Parse("2020-04-25T03:34:00Z"),TaskDescription="Quality-focused intangible groupware",TaskType="ability"},
new Quote{QuoteType="RZ-936",Contact="Tabbatha",DueDate=DateTime.Parse("2018-07-04T18:29:40Z"),TaskDescription="Organic exuding superstructure",TaskType="real-time"},
new Quote{QuoteType="MY-936",Contact="Carmencita",DueDate=DateTime.Parse("2018-04-20T08:19:48Z"),TaskDescription="Streamlined modular toolset",TaskType="Focused"},
new Quote{QuoteType="JZ-146",Contact="Aloisia",DueDate=DateTime.Parse("2018-08-07T06:20:18Z"),TaskDescription="Synergized background instruction set",TaskType="dynamic"},
new Quote{QuoteType="LQ-972",Contact="Carley",DueDate=DateTime.Parse("2017-01-30T17:19:44Z"),TaskDescription="Networked needs-based open architecture",TaskType="Visionary"},
new Quote{QuoteType="MF-911",Contact="Elizabeth",DueDate=DateTime.Parse("2019-09-26T05:05:20Z"),TaskDescription="Triple-buffered fresh-thinking time-frame",TaskType="function"},
new Quote{QuoteType="EM-109",Contact="Aura",DueDate=DateTime.Parse("2018-08-08T10:26:18Z"),TaskDescription="Re-engineered zero administration framework",TaskType="eco-centric"},
new Quote{QuoteType="ME-163",Contact="Elijah",DueDate=DateTime.Parse("2017-03-21T16:18:20Z"),TaskDescription="Profit-focused clear-thinking collaboration",TaskType="coherent"},
new Quote{QuoteType="LK-001",Contact="Kelci",DueDate=DateTime.Parse("2017-03-31T02:03:47Z"),TaskDescription="Mandatory secondary initiative",TaskType="time-frame"},
new Quote{QuoteType="MY-229",Contact="Grantham",DueDate=DateTime.Parse("2018-03-26T02:37:08Z"),TaskDescription="Front-line 4th generation functionalities",TaskType="Organized"},
new Quote{QuoteType="AZ-462",Contact="Tanner",DueDate=DateTime.Parse("2017-12-10T09:42:18Z"),TaskDescription="Multi-tiered full-range matrix",TaskType="context-sensitive"},
new Quote{QuoteType="CW-483",Contact="Katina",DueDate=DateTime.Parse("2017-06-16T10:07:27Z"),TaskDescription="Balanced fault-tolerant circuit",TaskType="logistical"},
new Quote{QuoteType="EK-397",Contact="Way",DueDate=DateTime.Parse("2018-12-09T17:16:02Z"),TaskDescription="Devolved coherent throughput",TaskType="hardware"},
new Quote{QuoteType="GP-364",Contact="Hyacinthe",DueDate=DateTime.Parse("2017-03-17T22:47:12Z"),TaskDescription="Multi-channelled web-enabled info-mediaries",TaskType="Cloned"},
new Quote{QuoteType="NW-130",Contact="Adrian",DueDate=DateTime.Parse("2017-12-11T07:00:14Z"),TaskDescription="Implemented explicit portal",TaskType="Universal"},
new Quote{QuoteType="FC-448",Contact="Gilli",DueDate=DateTime.Parse("2020-01-17T12:38:23Z"),TaskDescription="User-friendly motivating attitude",TaskType="Public-key"},
new Quote{QuoteType="JE-031",Contact="Anders",DueDate=DateTime.Parse("2020-06-15T17:43:13Z"),TaskDescription="Progressive real-time Graphical User Interface",TaskType="Monitored"},
new Quote{QuoteType="BO-212",Contact="Annaliese",DueDate=DateTime.Parse("2018-10-20T01:52:32Z"),TaskDescription="Versatile maximized archive",TaskType="database"},
new Quote{QuoteType="FX-271",Contact="Vail",DueDate=DateTime.Parse("2018-02-13T02:23:59Z"),TaskDescription="Function-based client-server info-mediaries",TaskType="Object-based"},
new Quote{QuoteType="CB-015",Contact="Koral",DueDate=DateTime.Parse("2018-03-26T03:19:10Z"),TaskDescription="Stand-alone motivating focus group",TaskType="array"},
new Quote{QuoteType="ZJ-838",Contact="Alethea",DueDate=DateTime.Parse("2019-06-11T00:10:33Z"),TaskDescription="Organized mobile encoding",TaskType="Fundamental"},
new Quote{QuoteType="ZD-542",Contact="Sharona",DueDate=DateTime.Parse("2019-08-25T12:50:57Z"),TaskDescription="Sharable eco-centric service-desk",TaskType="installation"},
new Quote{QuoteType="DN-323",Contact="Nobe",DueDate=DateTime.Parse("2018-12-22T13:45:18Z"),TaskDescription="Integrated well-modulated attitude",TaskType="content-based"},
new Quote{QuoteType="KW-644",Contact="Willem",DueDate=DateTime.Parse("2020-05-25T03:40:28Z"),TaskDescription="Versatile grid-enabled local area network",TaskType="Re-engineered"},
new Quote{QuoteType="UR-754",Contact="Ethelred",DueDate=DateTime.Parse("2018-10-04T16:40:33Z"),TaskDescription="Synergistic attitude-oriented concept",TaskType="knowledge user"},
new Quote{QuoteType="KQ-047",Contact="Barnett",DueDate=DateTime.Parse("2018-06-28T21:35:53Z"),TaskDescription="Devolved even-keeled concept",TaskType="Multi-layered"},
new Quote{QuoteType="BV-585",Contact="Maxi",DueDate=DateTime.Parse("2017-03-13T07:26:35Z"),TaskDescription="Open-architected upward-trending moderator",TaskType="Configurable"},
new Quote{QuoteType="IA-839",Contact="Gaston",DueDate=DateTime.Parse("2019-08-10T00:52:11Z"),TaskDescription="Extended content-based paradigm",TaskType="Enterprise-wide"},
new Quote{QuoteType="MF-780",Contact="Mag",DueDate=DateTime.Parse("2019-02-04T01:20:27Z"),TaskDescription="Down-sized directional adapter",TaskType="solution"},
new Quote{QuoteType="WG-707",Contact="Morganne",DueDate=DateTime.Parse("2019-10-08T00:18:53Z"),TaskDescription="Managed 24 hour system engine",TaskType="object-oriented"},
new Quote{QuoteType="OV-214",Contact="Cullin",DueDate=DateTime.Parse("2019-12-13T06:49:47Z"),TaskDescription="Organic encompassing algorithm",TaskType="help-desk"},
new Quote{QuoteType="CN-364",Contact="Storm",DueDate=DateTime.Parse("2019-03-23T19:10:25Z"),TaskDescription="Customizable motivating hub",TaskType="contextually-based"},
new Quote{QuoteType="SP-750",Contact="Giffie",DueDate=DateTime.Parse("2020-03-17T04:29:48Z"),TaskDescription="Managed needs-based time-frame",TaskType="demand-driven"},
new Quote{QuoteType="YA-456",Contact="Mordecai",DueDate=DateTime.Parse("2017-08-21T11:58:33Z"),TaskDescription="Progressive asynchronous software",TaskType="task-force"},
new Quote{QuoteType="KR-609",Contact="Phillida",DueDate=DateTime.Parse("2019-07-25T05:04:34Z"),TaskDescription="Innovative maximized model",TaskType="Enterprise-wide"},
new Quote{QuoteType="KV-325",Contact="Tanhya",DueDate=DateTime.Parse("2018-05-06T18:19:44Z"),TaskDescription="Stand-alone hybrid function",TaskType="bottom-line"},
new Quote{QuoteType="VH-961",Contact="Cortney",DueDate=DateTime.Parse("2020-01-01T07:39:13Z"),TaskDescription="Inverse web-enabled flexibility",TaskType="Persistent"},
new Quote{QuoteType="BG-232",Contact="Enriqueta",DueDate=DateTime.Parse("2017-08-28T02:46:21Z"),TaskDescription="Compatible incremental structure",TaskType="impactful"},
new Quote{QuoteType="AR-857",Contact="Tersina",DueDate=DateTime.Parse("2016-10-15T10:15:14Z"),TaskDescription="Automated executive Graphical User Interface",TaskType="4th generation"},
new Quote{QuoteType="FH-610",Contact="Ivor",DueDate=DateTime.Parse("2017-11-27T15:19:13Z"),TaskDescription="Enhanced bifurcated website",TaskType="systematic"},
new Quote{QuoteType="OK-741",Contact="Sheffy",DueDate=DateTime.Parse("2020-06-22T06:00:46Z"),TaskDescription="Fundamental 6th generation standardization",TaskType="function"},
new Quote{QuoteType="XO-568",Contact="Wendy",DueDate=DateTime.Parse("2017-09-16T23:11:43Z"),TaskDescription="Open-architected directional Graphic Interface",TaskType="Organized"},
new Quote{QuoteType="KR-985",Contact="Peterus",DueDate=DateTime.Parse("2019-09-17T20:43:58Z"),TaskDescription="Organized context-sensitive ability",TaskType="executive"},
new Quote{QuoteType="IC-285",Contact="Rosina",DueDate=DateTime.Parse("2017-04-09T08:13:01Z"),TaskDescription="Cross-platform neutral benchmark",TaskType="project"},
new Quote{QuoteType="BE-546",Contact="Hannie",DueDate=DateTime.Parse("2018-06-16T23:43:12Z"),TaskDescription="Multi-lateral intermediate contingency",TaskType="functionalities"},
new Quote{QuoteType="BL-443",Contact="Art",DueDate=DateTime.Parse("2017-02-10T19:46:27Z"),TaskDescription="Quality-focused background architecture",TaskType="flexibility"},
new Quote{QuoteType="EC-960",Contact="Livia",DueDate=DateTime.Parse("2018-07-25T07:19:36Z"),TaskDescription="Switchable dedicated knowledge user",TaskType="full-range"},
new Quote{QuoteType="VI-405",Contact="Tynan",DueDate=DateTime.Parse("2017-06-21T11:18:08Z"),TaskDescription="Secured leading edge capability",TaskType="extranet"},
new Quote{QuoteType="ZG-164",Contact="Jolene",DueDate=DateTime.Parse("2018-11-16T21:09:05Z"),TaskDescription="Automated full-range knowledge base",TaskType="Innovative"},
new Quote{QuoteType="NV-298",Contact="Yevette",DueDate=DateTime.Parse("2016-10-19T17:39:02Z"),TaskDescription="Diverse hybrid budgetary management",TaskType="Reactive"},
new Quote{QuoteType="GT-233",Contact="Yul",DueDate=DateTime.Parse("2019-04-23T10:00:20Z"),TaskDescription="Ameliorated even-keeled protocol",TaskType="global"}
            };

            quotes.ForEach(q => context.Quotes.Add(q));
            context.SaveChanges();
        }
    }
}
